### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by cookie-is-yummy**

### CODE REVIEW

**Review by Bryzizzle — COMMENTED** [review]
Simply Changing fonts I suppose?

**Comment by cookie-is-yummy** [comment]
> Simply Changing fonts I suppose?

Yep

**Comment by Bryzizzle** [comment]
It looks good, did someone ask you to change the fonts?

**Comment by cookie-is-yummy** [comment]
Yeah

**Comment by cookie-is-yummy** [comment]
Still don't see the changes idk why tho

**Review by Bryzizzle — APPROVED** [review]

**Comment by cookie-is-yummy** [comment]
yay

**Pull request merged**
